#!/bin/sh
# postinst script for trigger
#
# see: dh_installdeb(1)

set -e

configure() {
  adduser \
    --quiet \
    --system \
    --home /opt/proxette \
    --no-create-home \
    --shell /bin/bash \
    --group \
    --gecos "MyGov Authenticating Proxy" \
    proxette
}

case "$1" in
    configure)
      configure
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
